In [5]:
import numpy as np
def np_print(arr):
    txt='''
    shape : {}
    ndim : {}
    dtype : {}
    data : \n {}
    '''.format(arr.shape,arr.ndim,arr.dtype,arr)
    print(txt)

# 배열정렬
- sort(axis=-1)메서드: axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis=-1): 현재 배열의 마지막 axis
    - axis=0: 열 단위 정렬
    - axis=1: 행 단위 정렬
    - 원번 객체에 정렬 결과가 반영됨
- np.sort(axis=-1): axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis=-1): 현재 배열의 마지막 axis
    - axis=0: 열 단위 정렬
    - axis=1: 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
- np.argsort(arr): 정렬 순서를 반환함
    - 기본값(axis=-1): 현재 배열의 마지막 axis
    - axis=0: 열 단위 정렬
    - axis=1: 행 단위 정렬 

In [6]:
#1차원 배열 생성
#아이템: 0,1,2,3,4
x=np.arange(0,5)
np_print(x)


    shape : (5,)
    ndim : 1
    dtype : int32
    data : 
 [0 1 2 3 4]
    


In [7]:
#아이템 순서를 뒤집어서 나열
x=x[::-1]

In [8]:
x

array([4, 3, 2, 1, 0])

In [9]:
#arr.sort(): 원본 객체에 저장됨을 주의
x.sort()

In [10]:
x

array([0, 1, 2, 3, 4])

In [11]:
x[::-1]

array([4, 3, 2, 1, 0])

In [13]:
#다시 오름차순 정렬
x1=np.sort(x)
np_print(x1)


    shape : (5,)
    ndim : 1
    dtype : int32
    data : 
 [0 1 2 3 4]
    


In [32]:
#아이템: 0이상 10미만의 범위에서 5개의 무작위 정수값
#구조 ::1d=>5개
a=np.random.randint(0,10,size=5)
np_print(a)


    shape : (5,)
    ndim : 1
    dtype : int32
    data : 
 [5 0 1 3 0]
    


In [33]:
#오름차순 정렬
np.sort(a)

array([0, 0, 1, 3, 5])

In [34]:
np.argsort(a) #정렬된 순서의 번호 추출 ex) 9는 2번째에 위치한다 

array([0, 0, 1, 3, 5])

In [35]:
#내림차순 정렬
a.sort() #1,7,7,8,9
a=a[::-1]
a

array([5, 3, 1, 0, 0])

In [36]:
#오름차순된 정렬 순서
np.sort(a)

array([0, 0, 1, 3, 5])

In [37]:
a[a.argsort()]

array([0, 0, 1, 3, 5])

In [38]:
#아이템: 0이상 1미만의 범위에서 무작위 실수값을 가지는 3*3
#np.random.random
a=np.random.random((3,3))
b=np.random.random((3,3))
np_print(a)
np_print(b)


    shape : (3, 3)
    ndim : 2
    dtype : float64
    data : 
 [[0.04215144 0.29587498 0.4299246 ]
 [0.71377853 0.80889175 0.56431649]
 [0.53958289 0.15402463 0.29319309]]
    

    shape : (3, 3)
    ndim : 2
    dtype : float64
    data : 
 [[0.27025327 0.13928517 0.56087768]
 [0.78549828 0.38194126 0.36624971]
 [0.45677565 0.41785153 0.48732057]]
    


### 2차원 배열
- 기본값 axis=-1
- 현재 배열의 axis=0,1
- 마지막 axis=1(행기준 정렬)

In [39]:
#기본방향: 행 방향 정렬
np.sort(b)

array([[0.13928517, 0.27025327, 0.56087768],
       [0.36624971, 0.38194126, 0.78549828],
       [0.41785153, 0.45677565, 0.48732057]])

In [40]:
#열 기준 정렬
np.sort(a,axis=0)

array([[0.04215144, 0.15402463, 0.29319309],
       [0.53958289, 0.29587498, 0.4299246 ],
       [0.71377853, 0.80889175, 0.56431649]])

In [42]:
#열 기준 내림차순 정렬
np.sort(a,axis=0)[::-1]

array([[0.71377853, 0.80889175, 0.56431649],
       [0.53958289, 0.29587498, 0.4299246 ],
       [0.04215144, 0.15402463, 0.29319309]])

In [48]:
a #원본은 바뀌지 않음

array([[0.04215144, 0.29587498, 0.4299246 ],
       [0.71377853, 0.80889175, 0.56431649],
       [0.53958289, 0.15402463, 0.29319309]])

In [44]:
a[:,0].argsort()[::-1] #a[:,0]: 첫번째 열

array([1, 2, 0], dtype=int64)

In [50]:
#첫번째 칼럼을 기준으로 내림차순 정렬1
a[a[:,0].argsort()[::-1]]

array([[0.71377853, 0.80889175, 0.56431649],
       [0.53958289, 0.15402463, 0.29319309],
       [0.04215144, 0.29587498, 0.4299246 ]])

In [52]:
#첫번째 칼럼을 기준으로 내림차순 정렬2
a[(-a[:,0]).argsort()]

array([[0.71377853, 0.80889175, 0.56431649],
       [0.53958289, 0.15402463, 0.29319309],
       [0.04215144, 0.29587498, 0.4299246 ]])

# 인덱싱(Indexing), 슬라이싱(Slicing)
## 1. 인덱싱: 하나의 요소에 대해 참조(접근/확인)
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열: 인덱스 1개
    - 2차원 배열: 인덱스 2개
    - 3차원 배열: 인덱스 3개
- 인덱싱으로 참조한 요소에 대해 수정 가능
- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [53]:
#아이템: 0부터 23까지 1씩 증가하는 값
#구조: 1차원
arr=np.arange(0,24,1)
np_print(arr)


    shape : (24,)
    ndim : 1
    dtype : int32
    data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [54]:
#1차원 배열 인덱싱: 1번 인덱스 요소
arr[1]

1

In [55]:
#1차원 배열 인덱싱: 마지막 인덱스 요소
arr[-1]

23

In [56]:
#1차원 배열 인덱싱을 통한 값 수정
arr[-1]=100
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [57]:
#배열 arr 4*6 형태로 변환하여 2차원 배열 생성
#arr.reshape(row,col)
arr2=arr.reshape(4,6)
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22, 100]])

In [58]:
#2차원 배열의 인덱싱: 2d_array[행,열(생략가능)]
#하나의 행에 접근: 1행
#반환값: 1d array
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [59]:
#하나의 열에 접근: 모든 행에 대해 선택한 후 열 인덱스 지정
#반환값: 1d array
arr2[:,0]

array([ 0,  6, 12, 18])

In [61]:
#하나의 값에 접근
#3행 3열
arr2[2,2]

14

In [62]:
#여러 개의 행에 접근
#여러 개의 인덱스를 리스트로 묶어서 인덱싱
#인덱스: 1,3인 행에 접근
arr2[[1,2]]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [64]:
#여러 개의 열에 접근
#인덱스: 0,2번 열
arr2[:,[0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [65]:
#2차원 배열 인덱싱을 통한 값 수정
#하나의 행/열에 대해 모두 동일한 값으로 수정: 단일 값
#서로 다른 값으로 수정: array, list => 참조한 배열 아이템 개수 = 전달하는 객체 아이템 개수

In [66]:
#하나의 값으로 수정
arr2[0]=9
arr2

array([[  9,   9,   9,   9,   9,   9],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22, 100]])

In [67]:
#여러 개의 값으로 수정
arr2[0]=[0,1,2,9,9,9]
arr2

array([[  0,   1,   2,   9,   9,   9],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22, 100]])

In [68]:
#3차원 배열 생성
#아이템: 0이상 24미만의 정수
#구조: 2개층 4행 3열
arr3=np.arange(0,24).reshape((2,4,3))
np_print(arr3)


    shape : (2, 4, 3)
    ndim : 3
    dtype : int32
    data : 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
    


In [69]:
#3차원 배열 인덱싱: 3d_array[층,행,열]
#첫번째 층에 접근
arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
#첫번째 층, 2행에 접근
arr3[0,1,0]

3

In [72]:
arr3[0][1][0]

3

In [73]:
#3차원 배열 인덱싱을 통한 값 수정
#동일한 값으로 수정
arr3[0]=1
arr3

array([[[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [75]:
#하나의 층에 대해 서로 다른 값으로 수정:
#리스트로 2d array: 다차원리스트
arr3[0]=[[10,1,10],
        [1,10,1],
        [10,1,10],
        [1,1,10]]
arr3

array([[[10,  1, 10],
        [ 1, 10,  1],
        [10,  1, 10],
        [ 1,  1, 10]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [76]:
#인덱스 배열을 전달하여 여러 개의 요소 참조
#기존 인덱싱 방법
#arr3 1번째 층, 1번째 행, 1번째 아이템
#arr3 1번째 층, 2번째 행, 2번째 아이템
#arr3 1번째 층, 3번째 행, 3번째 아이템
arr3[0,0,0] #10
arr3[0,1,1] #10
arr3[0,2,2] #10

10

In [84]:
#여러 개의 인덱싱을 자료형으로 배열에 전달
#3d_array[층1,행1,열1],[층2,행2,열2],[층3,행3,열3]
#3d_array[[층],[행],[열]]
arr3[0,[[0,1],[1,2]],[[0,1],[1,2]]]

array([[10, 10],
       [10, 10]])

# 2. 슬라이싱: 여러개의 요소에 대해 참조
- axis 별로 범위 지정
    - from_index: 시작 인덱스(포함),0일 경우 생략 가능
    - to_index: 종료 인덱스(미포함), 마지막 인덱스일 경우 생략 가능
    - step: 연속되지 않은 범위의 경우 간격 지정
- 열만 조회할 경우: 전체 행에 슬라이싱으로 접근 후 특정 열을 조회

In [85]:
#아이템: 0이상 23부터 1씩 증가하는 정수
#구조: 1d
a=np.arange(0,24)
np_print(a)


    shape : (24,)
    ndim : 1
    dtype : int32
    data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [86]:
#1차원 배열 슬라이싱: 1번 인덱스부터 4번 인덱스까지 접근
a[1:5]

array([1, 2, 3, 4])

In [89]:
#간격 지정: 기본값=1
#1~4번 인덱스 $간격2
a[1:5:2]

array([1, 3])

In [91]:
a2=a.reshape(6,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [92]:
#2차원 배열 슬라이싱: 1행(0)부터 4행(3)까지
#2d_array[행:행:간격,열:열:간격]
a2[:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
a2[:4:2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [95]:
#행,열에 대해 모두 부분적 슬라이싱
#1행~4행 & 2열~4열
a2[:4,1:4]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [96]:
#서로 다른 결과
#행에 대해서 슬라이싱을 2번 한 결과
a2[:4][1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
#2차원 배열 슬라이싱을 통한 값 수정
#부분 배열 생성
#1행~4행 & 2열~4열
sample=a2[:4,1:]
sample

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [99]:
#2~3 & 0~1
#333
sample[2:3,0:1]=333
sample

array([[  1,   2,   3],
       [  5,   6,   7],
       [333,  10,  11],
       [ 13,  14,  15]])

In [100]:
#2차원 배열 슬라이싱: 연속되지 않은 범위의 열에 대한 인덱싱
#step1. 전체 행에 접근
#step2. 멀티 인덱싱
arr2[:,[1,-1]] #2열, 마지막 열

array([[  1,   9],
       [  7,  11],
       [ 13,  17],
       [ 19, 100]])

## 연습문제

아래 정보는 학생들의 학번,영어,국어,수학 성적 정보<br>
해당 정보를 첫번째 행에 학번, 두번째 행에 열어, 세번째 행에 국어, 네번째 행에 수학 성적을 저장한 배열로 만들고 학생별로 영어 성적을 오름차순 기준으로 각 열을 정렬하세요

학번 1 2 3 4<br>
영어 70 97 45 56<br> 
국어 87 84 33 67<br>
수학 46 80 75 78<br>

In [103]:
grade=np.array(([1,2,3,4],[70,97,45,56],[87,84,33,67],[46,80,75,78]))
grade

array([[ 1,  2,  3,  4],
       [70, 97, 45, 56],
       [87, 84, 33, 67],
       [46, 80, 75, 78]])

In [104]:
np.sort(grade[1])

array([45, 56, 70, 97])

In [107]:
#2번 행을 오름차순 했을 때 순서를 1번 행에 적용
#2번 행을 오름차순한 정렬 순서: np.argsort()
#1번 행에 적용
idx=np.argsort(grade[1])
idx

array([2, 3, 0, 1], dtype=int64)

In [114]:
#멀티 인덱싱은 위치바꾸기로 적용할 수 있다
grade[0]=grade[0][idx]
grade[1]=grade[1][idx]
grade[2]=grade[1][idx]
grade[3]=grade[1][idx]
grade

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [70, 97, 45, 56],
       [70, 97, 45, 56]])

In [112]:
arr1=np.array(([1,2,3,4],[70,97,45,56],[87,84,33,67],[46,80,75,78]))

In [116]:
#간단한 멀티인덱싱(열위치만 변화)
arr1[:,arr1[1].argsort()]  #arr1[:,[2,3,0,1]]이랑 같다=[행전체,열[2,3,0,1]]

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])

# 조건 색인(Boolean Indexing)
- 배열의 요소에 대해 조건을 적용하여 True, False로 조건에 대한 결과 반환
- True에 해당하는 요소만 조회하여 조건을 만족하는 결과 반환

In [118]:
#2차원 배열
a=a.reshape(6,4)
a

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8, 333,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [119]:
#10보다 큰 요소에 접근
#step1. 조건식을 연산자로 작성 -> 전체 배열에 적용
#반환값: T/F로 이루어진 전체 배열
a>10

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [120]:
#step2. boolean indexing 결과를 전체 배열에 대해서 인덱싱 처리
#반환값: 1d array =True 인 결과만 추출
a[a>10]

array([333,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23])

In [121]:
#개수
#len(), array.size
len(a[a>10])

14

In [122]:
a[a>10].size

14

In [124]:
#True=1이기 때문에 개수를 반환
(a>10).sum()

14

In [126]:
#짝수인 요소의 개수와 총합
len(a[a%2==0]) #개수
sum(a[a%2==0]) #총합

132

In [128]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [129]:
a[a%2==0].size

12

## 배열복사
- 인덱싱, 슬라이싱을 통해 반환된 배열은 원본 배열에 대해 독립적인 새로운 객체가 아닌 원본 배열과 종속적인 객체
- 원본과 독립적인 복사본인 배열을 생성: arr.copy() / np.copy(arr)

In [130]:
#파이썬 리스트 타입
a1=[1,2,3]
a2=[1,2,3]

In [131]:
b=a1
b

[1, 2, 3]

In [132]:
c=a2[:]
c[0]=10
c

[10, 2, 3]

In [133]:
a2 #서로 독립적

[1, 2, 3]

In [134]:
#리스트는 슬라이싱을 통해 복사

In [135]:
#Numpy 배열 타입
#아이템: 0부터 9까지의 범위에서 1씩 증가하는 값
#구조: 3*3
arr1=np.arange(0,9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [140]:
#슬라이싱으로 배열 복사
arr2=arr1[:,:]
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [141]:
np_print(arr2)


    shape : (3, 3)
    ndim : 2
    dtype : int32
    data : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
    


In [142]:
#원본 배열과의 관계: 종속적인 관계의 객체 생성
#1행 1열 값을 수정
arr2[0,0]=100
arr2

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [143]:
#독립적인 복사본 배열 생성
#배열 메서드: 원본객체.copy()
#numpy 함수:
arr3=arr1.copy()
arr3

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [144]:
arr3[0,0]=0
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
arr1

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])